#!/bin/bash
### BEGIN INIT INFO
# Provides:          fabqr_service
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/Restart/Stop FabQR service
### END INIT INFO


#    This file is part of FabQR. (https://github.com/FroChr123/FabQR)
#
#    FabQR is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    FabQR is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with FabQR.  If not, see <http://www.gnu.org/licenses/>.

# ##################################################################
# FabQR service script
# ##################################################################

# ##################################################################
# FUNCTIONS
# ##################################################################

# Function to show a text in console and to log it in logfile
# Argument 1: Text
function output_text
{
    output_text_std "$1"
    output_text_log "$1"
    return 0
}

# Function to show a text in console
# Argument 1: Text
function output_text_std
{
    TIMESTRING=$( date "+%Y-%m-%d %H:%M:%S" )
    echo "[$TIMESTRING] $1"
    return 0
}

# Function to log a text in logfile
# Argument 1: Text
function output_text_log
{
    TIMESTRING=$( date "+%Y-%m-%d %H:%M:%S" )
    if [ -e "/home/fabqr/fabqr.log" ]
    then
        echo "[$TIMESTRING] [SERVICE] $1" >> "/home/fabqr/fabqr.log"
    fi
    return 0
}

# Function to quit correctly
function quit_error
{
    output_text "[ERROR] QUIT FABQR INSTALLER WITH ERRORS"
    exit 1
    return 0
}

# ##################################################################
# MAIN
# ##################################################################

# FabQR service script start message
output_text "[INFO] START FABQR SERVICE SCRIPT"

# ##################################################################
# ROOT
# ##################################################################

# Check if script is executed as root, if not, quit with error message
if [[ $EUID -ne 0 ]]
then
    output_text "[ERROR] FabQR service script must be started as root, try sudo command"
    quit_error
fi

# ##################################################################
# START / RESTART / STOP FABQR
# ##################################################################

case $1 in
    start|restart)
        /home/fabqr/fabqr_start.sh
        ;;
    stop)
        /home/fabqr/fabqr_stop.sh
        ;;
    *)
        output_text_std "Usage: $0 {start|restart|stop}"
        ;;
esac

# Exit correctly without errors
output_text "[INFO] QUIT FABQR SERVICE SCRIPT SUCCESSFULLY"
exit 0